 
[build]
  command = "npm run build-prod" # Your build command here
  publish = "out" # Publish directory for Next.js production build

# If using next export and skipping .next directory requirement
[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

